services:
  postgres:
    image: postgres:16
    container_name: planeacion_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: COdeRYlUNCHvKqPAfBLSstqQPUAbNkMs
      POSTGRES_DB: planeacion_proyetos
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - red_sistema

  backend:
    build: .
    container_name: sistema_planeacion_api
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - red_sistema

volumes:
  postgres_data:

networks:
  red_sistema:
    driver: bridge
