const express = require("express")
const router = express.Router()
const ctrl = require("../controllers/cipController")
const evCtrl = require("../controllers/evidenciasController")

router.get("/catalogos/programas",ctrl.getCatProgramas)
router.get("/catalogos/subprogramas/:prog",ctrl.getCatSubprogramas)
router.get("/catalogos/partidas",ctrl.getCatPartidas)
router.get("/catalogos/fuentes",ctrl.getCatFuentes)
router.get("/catalogos/pmd/:dep_id",ctrl.getPMDPorDependencia)

router.get("/",ctrl.listar)
router.get("/:id",ctrl.obtener)
router.post("/",ctrl.crear)
router.put("/:id",ctrl.actualizar)
router.delete("/:id",ctrl.eliminar)
router.put("/:id/estado",ctrl.cambiarEstado)

router.get("/:id/desglose",ctrl.getDesglose)
router.post("/:id/desglose",ctrl.agregarDesglose)
router.put("/desglose/:did",ctrl.actualizarDesglose)
router.delete("/desglose/:did",    ctrl.eliminarDesglose)

router.get("/:id/metas",ctrl.getMetas)
router.post("/:id/metas",ctrl.agregarMeta)
router.put("/metas/:mid",ctrl.actualizarMeta)
router.delete("/metas/:mid",ctrl.eliminarMeta)
router.get("/catalogos/dependencias",ctrl.getDependencias)
router.get("/:id/exportar",ctrl.obtenerParaExportar)

router.put("/:id/enviar",ctrl.enviarRevision)
router.put("/:id/aprobar",ctrl.aprobarCIP)
router.put("/:id/rechazar",ctrl.rechazarCIP)
router.put("/:id/toggle-pdf",ctrl.togglePDF)
router.put("/:id/regresar-borrador",ctrl.regresarBorrador)
router.get("/:id/historial",ctrl.getHistorial)
router.get("/stats/revision",ctrl.getStatsRevision)
router.get("/:id/waypoints",ctrl.getWaypoints)
router.put("/:id/waypoints",ctrl.guardarWaypoints)

router.get("/:id/evidencias",evCtrl.listar)
router.post("/:id/evidencias",evCtrl.subir)
router.get("/:id/evidencias/:eid",evCtrl.obtener)
router.put("/:id/evidencias/:eid",evCtrl.actualizar)
router.delete("/:id/evidencias/:eid",evCtrl.eliminar)
router.get("/:id/evidencias/resumen",evCtrl.resumen)
module.exports = router