const express = require("express")
const router = express.Router()
const controller = require("../controllers/fichasController")

router.post("/crear", controller.crear)
router.get("/lista", controller.lista)
router.get("/porDependencia/:dependency_id", controller.porDependencia)
router.put("/actualizar/:id", controller.actualizar)
router.delete("/eliminar/:id", controller.eliminar)
router.get("/historial/:ficha_id", controller.historial)
router.get("/estrategias/:dependency_id", controller.estrategiasPorDependencia)
router.get("/lineas-por-dep/:dependency_id",   controller.lineasPorDependencia)
router.get("/datos-para-ficha/:planning_id/:anio", controller.datosParaFicha)
router.get("/lista-con-poa",                   controller.listaConPOA)
router.get("/ponderacion-estrategia/:dependency_id",          controller.ponderacionPorEstrategia)
router.get("/datos-estrategia/:strategy_id/:dependency_id",   controller.datosEstrategiaParaFicha)
router.get("/estrategias/:dependency_id",                     controller.estrategiasPorDependencia)
module.exports = router 